version: 0.2
env:
  variables:
    build_version: "0.1"
phases:
  install:
    commands:
      - echo install step...
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven
  pre_build:
    commands:
      - echo running mvn ...
      - mvn clean package
  build:
    commands:
      - echo build Docker image on `date`
      - curr_working_dir=`pwd`
      - docker build -t petclinic-spinnaker-jenkins:latest .
      - docker tag petclinic-spinnaker-jenkins:latest ibuchh/petclinic-spinnaker-jenkins:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to Dokcer Hub ...
      - docker push ibuchh/petclinic-spinnaker-jenkins:latest
